services:
  eventsourcingdb:
    image: thenativeweb/eventsourcingdb
    container_name: eventsourcingdb
    ports:
      - "3000:3000"
    command: >
      run
      --api-token=secret
      --data-directory-temporary
      --http-enabled
      --https-enabled=false
      --with-ui
    stdin_open: true
    tty: true
